apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-keycloak-deployment
spec:
  selector:
    matchLabels:
      app: demo-keycloak
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-keycloak
    spec:
      containers:
        - name: demo-keycloak
          image: demo-keycloak
          ports:
            - containerPort: 8080
          env: # Setting Environment Variables
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: realm
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: auth-server-url
            - name: KEYCLOAK_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: port
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: resource
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: demo-keycloak-svc
spec:
  selector:
    app: demo-keycloak
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
