apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:11
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: POSTGRESQL_USERNAME
              value: bn_keycloak
            - name: POSTGRESQL_DATABASE
              value: bitnami_keycloak
          volumeMounts:
            - name: postgresql-data
              mountPath: /bitnami/postgresql
          ports:
            - containerPort: 5432
        - name: keycloak
          image: bitnami/keycloak:19
          env:
            - name: KEYCLOAK_ADMIN_USER
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: keycloak
  type: LoadBalancer